# Generated by Django 2.2.1 on 2019-05-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20190526_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.CharField(max_length=20),
        ),
    ]
